// FIFA 3-letter code -> Korean country name (2026 World Cup participants).
export const KO_NAME_BY_CODE: Record<string, string> = {
  ALG: "알제리",
  ARG: "아르헨티나",
  AUS: "호주",
  AUT: "오스트리아",
  BEL: "벨기에",
  BIH: "보스니아",
  BRA: "브라질",
  CAN: "캐나다",
  CIV: "코트디부아르",
  COD: "콩고민주공화국",
  COL: "콜롬비아",
  CPV: "카보베르데",
  CRO: "크로아티아",
  CUW: "퀴라소",
  CZE: "체코",
  ECU: "에콰도르",
  EGY: "이집트",
  ENG: "잉글랜드",
  ESP: "스페인",
  FRA: "프랑스",
  GER: "독일",
  GHA: "가나",
  HAI: "아이티",
  IRN: "이란",
  IRQ: "이라크",
  JOR: "요르단",
  JPN: "일본",
  KOR: "대한민국",
  KSA: "사우디아라비아",
  MAR: "모로코",
  MEX: "멕시코",
  NED: "네덜란드",
  NOR: "노르웨이",
  NZL: "뉴질랜드",
  PAN: "파나마",
  PAR: "파라과이",
  POR: "포르투갈",
  QAT: "카타르",
  RSA: "남아프리카공화국",
  SCO: "스코틀랜드",
  SEN: "세네갈",
  SUI: "스위스",
  SWE: "스웨덴",
  TUN: "튀니지",
  TUR: "튀르키예",
  URU: "우루과이",
  USA: "미국",
  UZB: "우즈베키스탄",
};

export function koNameByCode(code: string | undefined, fallback: string): string {
  if (!code) return fallback;
  return KO_NAME_BY_CODE[code.toUpperCase()] ?? fallback;
}
